version: '3.8'

services:
  auth_service_db:
    image: postgres:15
    container_name: auth_service_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_service_user
      POSTGRES_PASSWORD: qwertyui
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '7500:5432'

  auth-service:
    image: auth_service:latest
    depends_on:
      - auth_service_db
    ports:
      - '8080:8080'
    volumes:
      - ./Config.toml:/app/Config.toml
      - ./logs:/app/logs
      # - ./public.key:/app/public.key
      # - ./private.crt:/app/private.crt
    environment:
      BAL_CONFIG_FILES: /app/Config.toml


volumes:
  pgdata: